// The content of this file was generated by IBM Cloud
// Do not modify it as it might get overridden
const sequelize = require('../../models/index').sequelize
module.exports = function(app, server){

    require('./swagger')(app);
    require('./image-check')(app);
    require('./health')(app);

    app.get('/buildings', (req, res) => {
      sequelize
        .query('select * from building where img_url like "%bucket-yyny%" and created_at > "2018-09-16T08:30:00Z" order by created_at desc')
        .then(buildings => res.json(buildings[0]))
        .catch(err => res.sendStatus(500))
    })
};
